# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Silvie, Wrote a Blog
description: >- # this means to ignore newlines until "baseurl:"
  A wiki-style Grand Archive fan blog, run by PichuFan.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.silvie.org" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ItsSilvie
instagram_username: pichucollector
# Build settings
theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "cards"
    values:
      categories: cards
      hidden: true
      layout: "post"
      excerpt: A card from the Grand Archive trading card game. Find all variants of the card here.
  - scope:
      path: "sets"
    values:
      categories: sets
      hidden: true
      layout: "post"
      excerpt: A set in the Grand Archive trading card game. See the full set list here.
  - scope:
      path: "pack-simulator"
    values:
      categories: sets
      hidden: true
      layout: pack-simulator
      date: 2022-06-28 16:44:00 +0100
      categories: sets
      image: /assets/images/sets/000-all-sets/thumbnail.png


sass:
  sass_dir: _sass
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
